### ISSUE TITLE
Request for TLS Certificate Generation with External Name Servers Support

### ISSUE THREAD

**Issue by handshake-enthusiast** [neuenet/dolo-www#1]
Hello! First off, I'd like to commend you on the Dolo app; it's a fantastic tool. I'm interested in generating a TLS certificate for my site hosted at https://git/, but I've noticed that the app currently supports TLS certificate generation only for domains using its own name servers. In my situation, I prefer to use Varo as my name server provider, as my domain is managed there (https://hns.cymon.de/name/git). Would it be possible to extend support for TLS certificate generation for domains hosted on external name servers like Varo?  

<img width="987" alt="Screenshot 2024-02-26 at 23 23 22" src="https://github.com/neuenet/dolo-www/assets/104037912/60e6643a-513b-4917-9130-b98d32a769c7">

<img width="987" alt="Screenshot 2024-02-26 at 23 23 49" src="https://github.com/neuenet/dolo-www/assets/104037912/836ffe93-f56f-4a94-975d-0909406d8e40">

**Comment by NetOpWibby** [comment]
@handshake-enthusiast My apologies for not seeing your issue sooner (you should've made this issue on the [proper repo](https://github.com/neuenet/dolo-desktop))! Anyhoo, the upcoming changes to Handshake are not something I agree with so I'm taking a break as I figure out what's next.

The codebase is pretty organized so you should be able to fork and make the changes you want. Again, apologies for not getting back to you sooner.
